<?php
require_once('./dompdf/autoload.inc.php');
require 'db_connect.php';

use Dompdf\Dompdf;

$dompdf = new Dompdf();

$selecthotel = "SELECT hotel.hotelUid,  hotel.hotelName, hotel.hotelDesc
                FROM hotel";

$resulthotel = mysqli_query($conn, $selecthotel);

$html = '<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>  Hotels Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }

        header {
            text-align: center;
            margin-bottom: 20px;
        }

        h3 {
            color: #3498db;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th, td {
            border: 1px solid #ddd;
            padding: 12px;
            text-align: left;
        }

        th {
            background-color: #3498db;
            color: white;
        }

        .footer {
            margin-top: 20px;
            text-align: center;
            color: #555;
        }
    </style>
</head>
<body>

    <header>
        <h3>Hotels Report</h3>
    </header>

    <table>
        <thead>
            <tr>
                <th>Hotel ID</th>
                <th>Hotel Name</th>
                <th>Hotel Des</th>
            </tr>
        </thead>
        <tbody>';

while ($row = mysqli_fetch_assoc($resulthotel)) {
    $html .= '<tr>';
    $html .= '<td>' . $row['hotelUid'] . '</td>';
    $html .= '<td>' . $row['hotelName'] . '</td>';
    $html .= '<td>' . $row['hotelDesc'] . '</td>';
    
    if ($row['hotelName'] == 1) {
        $html .= '<span >Paid</span>';
    } elseif ($row['hotelName'] == 2) {
        $html .= '<span>Unpaid</span>';
    } 

    
    
    $html .= '</tr>';
}

$html .= '</tbody>
    </table>

    <div class="footer">
        <h6>Generated By CTO on ' . date('Y-m-d') . '</h6>
    </div>

</body>
</html>';

$dompdf->loadHTML($html);

$dompdf->setPaper('A4', 'landscape');

$dompdf->render();

$dompdf->stream();
?>
