<?php
require_once('./dompdf/autoload.inc.php');
require 'db_connect.php';

use Dompdf\Dompdf;

$dompdf = new Dompdf();

$selectcustomer = "SELECT customer.custUid,  customer.custName, customer.custAge,customer.custPlace,customer.custGender
                FROM customer";

$resultcustomer = mysqli_query($conn, $selectcustomer);

$html = '<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>  customer Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }

        header {
            text-align: center;
            margin-bottom: 20px;
        }

        h3 {
            color: #3498db;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th, td {
            border: 1px solid #ddd;
            padding: 12px;
            text-align: left;
        }

        th {
            background-color: #3498db;
            color: white;
        }

        .footer {
            margin-top: 20px;
            text-align: center;
            color: #555;
        }
    </style>
</head>
<body>

    <header>
        <h3>customer Report</h3>
    </header>

    <table>
        <thead>
            <tr>
                <th>Customer ID</th>
                <th>Customer Name</th>
                <th>Customer Age</th>
                <th>Customer Plase</th>
                
            </tr>
        </thead>
        <tbody>';

while ($row = mysqli_fetch_assoc($resultcustomer)) {
    $html .= '<tr>';
    $html .= '<td>' . $row['custUid'] . '</td>';
    $html .= '<td>' . $row['custName'] . '</td>';
    $html .= '<td>' . $row['custAge'] . '</td>';
    $html .= '<td>' . $row['custPlace'] . '</td>';
   
    
    if ($row['custUid'] == 1) {
        $html .= '<span ></span>';
    } elseif ($row['custName'] == 2) {
        $html .= '<span>Unpaid</span>';
    } 

    $html .= '</td>';
   
    $html .= '</tr>';
    
    
}

$html .= '</tbody>
    </table>

    <div class="footer">
        <h6>Generated By CTO on ' . date('Y-m-d') . '</h6>
    </div>

</body>
</html>';

$dompdf->loadHTML($html);

$dompdf->setPaper('A4', 'landscape');

$dompdf->render();

$dompdf->stream();
?>
